### ISSUE TITLE
register button don't respond 

### ISSUE THREAD

**Issue by niradler** [serverless-stack/isserverlessready#2]
Hi, tried a different combination and the button still doesn't respond.
![image](https://user-images.githubusercontent.com/6292980/205446597-bbf2e430-a17a-4ab5-83bc-1d21ef02e40e.png)

**Comment by niradler** [comment]
incognito solve it, I think one of the chrome extensions breaks it.

**Comment by jayair** [comment]
Oh weird. Do you know which one?

**Comment by niradler** [comment]
I think one of the privacy extensions
